### ISSUE TITLE
Unable to use rblxRP on MacOS

### ISSUE THREAD

**Issue by catgirlinspace** [theLMGN/rblxRP#24]
Opening `rblxRP.app` displays this modal. 
![image](https://user-images.githubusercontent.com/13684891/151676178-ea385971-3889-4870-9f98-ce502f012b7f.png)
I have attempted to investigate logs to figure out the cause but I was unsuccessful. 
![image](https://user-images.githubusercontent.com/13684891/151676386-00a93be5-2799-485f-816a-f612cfd2d4ba.png)

**Comment by eth0fox** [comment]
There's a bug in macOS where donloading app files will sometimes cause that error.

The fix is to first move the application to your Applications folder, and then run this command in the Terminal (Applications >  Utilities > Terminal)

```
xattr -cr /Applications/rblxRP.app
```

**Comment by catgirlinspace** [comment]
this fixed the issue, thanks! i've never needed to use a command like this for any other application though. is `pkg` making a bad `.app` somehow?

**Comment by eth0fox** [comment]
afaik it's because macOS applies a 'quarantine' bit to files downloaded through Safari (and contents of downloaded zip files), and will refuse to open applications with the quarantine bit set. Contents of DMG files do not have the same flag. 

xattr -cr removes all extended attributes from a file, including the quarantine bit, so it can be opened.

**Comment by catgirlinspace** [comment]
That's kinda annoying, is there a way `pkg` can be configured to output a `.dmg` instead?
